import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { backgroundColor: "#F3FAFE", padding: 20, paddingBottom: 110 },
  eyebrow: {
    color: "#0081CC",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  title: { color: "#12344A", fontSize: 34, fontWeight: "800", marginTop: 6 },
  monthRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  monthText: { color: "#285A75", fontSize: 17, fontWeight: "700" },
  monthHint: { color: "#6D9AB3", fontSize: 14 },
  summaryCard: {
    backgroundColor: "#0081CC",
    borderRadius: 16,
    marginTop: 22,
    padding: 20,
  },
  summaryHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  summaryLabel: {
    color: "#DDF3FF",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 1,
  },
  summaryValue: {
    color: "#FFFFFF",
    fontSize: 36,
    fontWeight: "800",
    marginTop: 5,
  },
  summaryIcon: {
    alignItems: "center",
    backgroundColor: "#35A4D8",
    borderRadius: 20,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  summaryIconText: { color: "#FFFFFF", fontSize: 25, fontWeight: "700" },
  summaryDivider: { backgroundColor: "#4FB2DE", height: 1, marginVertical: 18 },
  summaryStats: { flexDirection: "row", justifyContent: "space-between" },
  summaryStat: { flex: 1 },
  summaryStatLabel: { color: "#DDF3FF", fontSize: 13 },
  summaryStatValue: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
    marginTop: 5,
  },
  sectionHeader: {
    alignItems: "flex-end",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    marginTop: 30,
  },
  sectionTitle: { color: "#12344A", fontSize: 22, fontWeight: "800" },
  sectionSubtitle: { color: "#527A91", fontSize: 15, marginTop: 3 },
  flavorCount: { color: "#0081CC", fontSize: 14, fontWeight: "700" },
  flavorRow: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    marginBottom: 12,
    padding: 16,
  },
  flavorInfo: { flex: 1 },
  flavorName: { color: "#12344A", fontSize: 18, fontWeight: "800" },
  flavorMeta: { color: "#527A91", fontSize: 14, marginTop: 5 },
  stockBadge: {
    alignItems: "flex-end",
    position: "absolute",
    right: 16,
    top: 15,
  },
  stockValue: { color: "#0081CC", fontSize: 24, fontWeight: "800" },
  stockLabel: { color: "#6D9AB3", fontSize: 12 },
  saleAction: { alignItems: "center", flexDirection: "row", marginTop: 15 },
  quantityInput: {
    backgroundColor: "#F0F8FD",
    borderColor: "#B7DFF2",
    borderRadius: 8,
    borderWidth: 1,
    color: "#12344A",
    height: 44,
    paddingHorizontal: 12,
    width: 74,
  },
  saleButton: {
    alignItems: "center",
    backgroundColor: "#0081CC",
    borderRadius: 8,
    flex: 1,
    height: 44,
    justifyContent: "center",
    marginLeft: 8,
  },
  saleButtonDisabled: { opacity: 0.65 },
  saleButtonText: { color: "#FFFFFF", fontSize: 14, fontWeight: "700" },
  errorBox: {
    backgroundColor: "#FFF1ED",
    borderRadius: 10,
    marginBottom: 12,
    padding: 12,
  },
  errorText: { color: "#A34432", fontSize: 14, lineHeight: 20 },
  retryText: {
    color: "#A34432",
    fontSize: 14,
    fontWeight: "800",
    marginTop: 8,
  },
  loader: { marginVertical: 20 },
  emptyState: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    padding: 24,
  },
  emptyTitle: { color: "#12344A", fontSize: 18, fontWeight: "800" },
  emptyText: {
    color: "#527A91",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 7,
    textAlign: "center",
  },
});
